Intheworld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud.urls')),
    path('', include('mvt.urls')),
]

mvt/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('mvt/', views.mvt),

    path('people/', views.person_list, name='person_list'),
    path('people/<pk>/', views.person_detail, name='person_detail'),
    path('passport/', views.passport_list, name='passport_list'),
    path('passport/<pk>/', views.passport_detail, name='passport_detail'),

    path('reporters/', views.reporter_list, name='reporter_list'),
    path('reporters/<pk>/', views.reporter_detail, name='reporter_detail'),
    path('articles/', views.article_list, name='article_list'),
    path('articles/<pk>/', views.article_detail, name='article_detail'),

    path('cars/', views.car_list, name='car_list'),
    path('car/<pk>/', views.car_detail, name='car_detail'),
    path('fuel/', views.fuel_list, name='fuel_list'),
    path('fuel/<pk>/', views.fuel_detail, name='fuel_detail'),
]

mvt/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return self.first_name


class Passport(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    passport_number = models.CharField(max_length=20)

    def __str__(self):
        return f'u chelaveka {self.person.first_name} yest id {self.passport_number}'


class Reporter(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return f'Reporter: {self.first_name}'


class Article(models.Model):
    headline = models.CharField(max_length=100)
    reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)

    def __str__(self):
        return f'Statya: {self.headline} by {self.reporter.first_name}'


class Fuel(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Car(models.Model):
    name = models.CharField(max_length=100)
    fuels = models.ManyToManyField(Fuel, related_name='cars')

    def __str__(self):
        return self.name

mvt/views.py
from django.shortcuts import render
from .models import Person, Passport, Reporter, Article, Fuel, Car


def person_list(request):
    people = Person.objects.all()
    return render(request, 'mvt/people.html', {'person_list': people})


def person_detail(request, pk):
    person = Person.objects.get(pk=pk)
    return render(request, 'mvt/person_detail.html', {'person': person})


def passport_list(request):
    passport = Passport.objects.all()
    return render(request, 'mvt/passport.html', {'passport_list': passport})


def passport_detail(request, pk):
    passport_number = Passport.objects.get(pk=pk)
    return render(request, 'mvt/passport_detail.html', {'passport_number': passport_number})


def reporter_list(request):
    reporter = Reporter.objects.all()
    return render(request, 'mvt/reporter_list.html', {'reporter_list': reporter})


def reporter_detail(request, pk):
    reporter = Reporter.objects.get(pk=pk)
    return render(request, 'mvt/reporter_detail.html', {'reporter': reporter})


def article_list(request):
    article = Article.objects.all()
    return render(request, 'mvt/article_list.html', {'article_list': article})


def article_detail(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'mvt/article_detail.html', {'article': article})


def fuel_list(request):
    fuel = Fuel.objects.all()
    return render(request, 'mvt/fuel_list.html', {'fuel_list': fuel})


def fuel_detail(request, pk):
    fuel = Fuel.objects.get(pk=pk)
    return render(request, 'mvt/fuel_detail.html', {'fuel': fuel})


def car_list(request):
    name = Car.objects.all()
    return render(request, 'mvt/car_list.html', {'car_list': name})


def car_detail(request, pk):
    name = Car.objects.get(pk=pk)
    return render(request, 'mvt/car_detail.html', {'car': name})



def mvt(request):
    if request.method == 'GET':
        return render(request, 'mvt/mvt.html')

mvt/templates/mvt/article_detail.html
{% block content %}
  <h1>{{ article.headline }}</h1>
  <h2>Reporter is {{ article.reporter.first_name }}</h2>
{% endblock %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>

</head>
<body>
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/articles/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>
</body>
</html>

mvt/templates/mvt/article_list.html
{% block content %}
  <h1>Article</h1>
  <ul>
    {% for article in article_list %}
      <li>
        <a href="{% url 'article_detail' article.pk %}">{{ article.headline }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>

</head>
<body>
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/mvt/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

</body>
</html>

mvt/templates/mvt/car_detail.html
{% block content %}
  <h1>{{ car.name }}</h1>
  <h2>Fuel Type</h2>
  <ul>
    {% for fuel in car.fuels.all %}
      <li>
        <a href="{% url 'fuel_detail' fuel.pk %}">{{ fuel.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/cars/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/car_list.html
{% block content %}
  <h1>Car Models</h1>
  <ul>
    {% for car in car_list %}
      <li>
        <a href="{% url 'car_detail' car.pk %}">{{ car.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/mvt/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/fuel_detail.html
{% block content %}
  <h2>ID Fuel: {{ fuel.id }}</h2>
  <h2>Fuel Type: {{ fuel.name }}</h2>
  <h2>Cars</h2>
  <ul>
    {% for car in fuel.cars.all %}
      <li>
       <a href="{% url 'car_detail' car.pk %}">{{ car.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/fuel/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/fuel_list.html
{% block content %}
  <h1>Fuel Type</h1>
  <ul>
    {% for fuel in fuel_list %}
      <li>
        <a href="{% url 'fuel_detail' fuel.pk %}">{{ fuel.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/mvt/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/mvt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>-_-</title>
       <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 0.6;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            color: #333;
        }
        header {
            background-color: #007bff;
            color: #fff;
            text-align: center;
            padding: 1rem 0;
            margin-bottom: 20px;
        }
        .container {
            width: 50%;
            max-width: 400px;
            margin: 0 auto;
            padding: 18px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(10,10,10,10.1);
        }
        .portfolio-item {
            margin-bottom: 15px;
            padding: 14px;
            background-color: #f9f9f9;
            border: 3px solid #ddd;
        }
    </style>
</head>
<body>
    <header>
        <h1>MVT</h1>
    </header>
    <div class="container">
        <div class="portfolio-item">
            <pre style="font-size:120%; font-family:verdana;">One to one</pre>
            <hr>
            <pre style="font-size:105%; font-family:verdana;"><p>Models:  Person  and  Passport</p></pre>
            <hr>
            <pre style="font-size:100%; font-family:verdana;"><a href="http://127.0.0.1:8000/people/">People list</a>          <a href="http://127.0.0.1:8000/passport/">Passports list</a></pre>
        </div>
        <div class="portfolio-item">
            <pre style="font-size:120%; font-family:verdana;">One to many</pre>
            <hr>
            <pre style="font-size:105%; font-family:verdana;"><p>Models:  Reporter  and  Article</p></pre>
            <hr>
            <pre style="font-size:100%; font-family:verdana;"><a href="http://127.0.0.1:8000/reporters/">Reporters list</a>          <a href="http://127.0.0.1:8000/articles/">Articles list</a></pre>
        </div>
        <div class="portfolio-item">
            <pre style="font-size:120%; font-family:verdana;">Many to many</pre>
            <hr>
            <pre style="font-size:105%; font-family:verdana;"><p>Models:  Car  and  Fuel</p></pre>
            <hr>
            <pre style="font-size:100%; font-family:verdana;"><a href="http://127.0.0.1:8000/cars/">Cars list</a>          <a href="http://127.0.0.1:8000/fuel/">Fuels list</a></pre>
            <hr>
        </div>
        <a style="font-size:100%; font-family:verdana;" href="http://127.0.0.1:8000/">—Back—</a>
    </div>

<!--    <table>-->
<!--        <tr>-->
<!--            <th>1</th>-->
<!--            <th>2</th>-->
<!--            <th>3</th>-->
<!--        </tr>-->
<!--    </table>-->
</body>
</html>

mvt/templates/mvt/passport.html
{% block content %}
  <h1>Passport</h1>
  <ul>
    {% for passport in passport_list %}
      <li>
        <a href="{% url 'passport_detail' passport.pk %}">Passport {{ passport.pk }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/mvt/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/passport_detail.html
{% block content %}
  <h1 style="font-size:120%; font-family:verdana;">Passport {{ passport_number.pk }}</h1>
  <p style="font-size:120%; font-family:verdana;">Number: {{ passport_number.passport_number }}</p>
  <p style="font-size:120%; font-family:verdana;">Person: {{ passport_number.person.first_name }}{{}}</p>
{% endblock %}
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/passport/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/people.html
{% block content %}
  <h1>People</h1>
  <ul>
    {% for person in person_list %}
      <li>
        <a href="{% url 'person_detail' person.pk %}">{{ person.first_name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/mvt/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/person_detail.html
{% block content %}
  <p style="font-size:120%; font-family:verdana;">{{ person.first_name }}</p>
  <p style="font-size:120%; font-family:verdana;">{{ person.last_name }}</p>
  <p style="font-size:120%; font-family:verdana;">ID number: {{ person.passport.passport_number }}</p>
{% endblock %}
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/people/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>

mvt/templates/mvt/reporter_detail.html
{% block content %}
  <h1>{{ reporter.last_name }} {{ reporter.first_name }}</h1>
  <h2>Article</h2>
  <ul>
    {% for article in reporter.article_set.all %}
      <li>
        <a href="{% url 'article_detail' article.pk %}">{{ article.headline }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>

</head>
<body>
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/reporters/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>
</body>
</html>

mvt/templates/mvt/reporter_list.html
{% block content %}
  <h1>Spisok Jurnalistov</h1>
  <ul>
    {% for reporter in reporter_list %}
      <li>
        <a href="{% url 'reporter_detail' reporter.pk %}">{{ reporter.first_name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>

</head>
<body>
<hr>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/mvt/">Back</a></pre>
<pre style="font-size:120%; font-family:verdana;"><a href="http://127.0.0.1:8000/">Menu</a></pre>
</body>
</html>